In [144]:
import os
import pandas as pd

In [145]:
folder_files = './data/processed/'

file_list = [os.path.join(folder_files, file) for file in os.listdir(folder_files) if file.endswith('.csv')]

df_2020 = pd.read_csv(file_list[0])
df_2021 = pd.read_csv(file_list[1])
df_2022 = pd.read_csv(file_list[2])

In [146]:
print(len(df_2020))
print(len(df_2021))
print(len(df_2022))

727
686
862

# Criação coluna ANOS_PM_

- 2020 ok

## 2022

ANOS_PM_2022 = 2022 - ANO_INGRESSO_2022

In [147]:
list_values_anos_pm_2022 = 2022 - df_2022['ANO_INGRESSO_2022']
df_2022.insert(2, 'ANOS_PM_2022', list_values_anos_pm_2022)
df_2022.head()

,NOME,ANO_INGRESSO_2022,ANOS_PM_2022,BOLSISTA_2022,FASE_2022,TURMA_2022,PONTO_VIRADA_2022,INDE_2022,PEDRA_2022,CG_2022,...,NOTA_PORT_2022,NOTA_MAT_2022,NOTA_ING_2022,QTD_AVAL_2022,REC_AVA_1_2022,REC_AVA_2_2022,REC_AVA_3_2022,REC_AVA_4_2022,NIVEL_IDEAL_2022,INDICADO_BOLSA_2022
0,ALUNO-2,2022,0,False,0,K,Não,7.676,Ametista,245,...,8.200,9.433,0.0,2,Mantido na Fase + Bolsa,Mantido na Fase atual,NaN,NaN,Fase 2 (5º e 6º ano),True
1,ALUNO-4,2022,0,False,2,J,Não,7.117,Ametista,451,...,5.000,5.167,0.0,3,Promovido de Fase,Mantido na Fase atual,Promovido de Fase,NaN,Fase 3 (7º e 8º ano),False
2,ALUNO-5,2019,3,False,2,L,Não,7.232,Ametista,415,...,6.667,7.500,0.0,3,Mantido na Fase atual,Promovido de Fase,Mantido na Fase atual,NaN,Fase 3 (7º e 8º ano),False
3,ALUNO-6,2022,0,False,2,K,Não,7.742,Ametista,221,...,3.000,8.000,0.0,3,Mantido na Fase atual,Promovido de Fase,Mantido na Fase atual,NaN,Fase 2 (5º e 6º ano),False
4,ALUNO-7,2022,0,False,1,U,Não,7.407,Ametista,357,...,4.667,6.500,0.0,2,Promovido de Fase,Promovido de Fase,NaN,NaN,Fase 2 (5º e 6º ano),False

## 2021

Não há nenhuma coluna com essa informação, apenas indica se é ingressante ou não. Opção é obter indiretamente dos outros dataframes

In [148]:
df_2021.head()

,NOME,INSTITUICAO_ENSINO_ALUNO_2021,FASE_2021,TURMA_2021,PONTO_VIRADA_2021,SINALIZADOR_INGRESSANTE_2021,INDE_2021,PEDRA_2021,IAA_2021,IEG_2021,...,IDA_2021,IPP_2021,IPV_2021,IAN_2021,REC_EQUIPE_1_2021,REC_EQUIPE_2_2021,REC_EQUIPE_3_2021,REC_EQUIPE_4_2021,NIVEL_IDEAL_2021,DEFASAGEM_2021
0,ALUNO-1,Rede Decisão,2,G,Não,Ingressante,7.319,Ametista,7.5,6.3,...,8.8,7.7,8.1,5.0,Promovido de Fase,Promovido de Fase,Mantido na Fase atual,Não avaliado,Nível 3 (7o e 8o ano),-1
1,ALUNO-3,Escola Pública,3,F,Não,Veterano,7.021,Ametista,7.1,6.9,...,5.6,7.3,7.2,10.0,Promovido de Fase,Promovido de Fase,Mantido na Fase atual,Não avaliado,Nível 3 (7o e 8o ano),0
2,ALUNO-5,Escola Pública,2,L,Não,Veterano,7.399,Ametista,7.4,7.5,...,5.4,8.5,7.4,10.0,Promovido de Fase,Mantido na Fase atual,Mantido na Fase atual,Não avaliado,Nível 2 (5o e 6o ano),0
3,ALUNO-8,Rede Decisão,5,L,Não,Veterano,8.269,Topázio,8.8,8.6,...,7.1,8.0,8.5,10.0,Promovido de Fase + Bolsa,Promovido de Fase,Promovido de Fase,Mantido na Fase atual,Nível 5 (1o EM),0
4,ALUNO-11,Rede Decisão,1,A,Sim,Veterano,8.990,Topázio,9.0,10.0,...,8.8,7.7,9.7,10.0,Promovido de Fase,Mantido na Fase atual,Mantido na Fase atual,Não avaliado,Nível 1 (4o ano),0

In [149]:
# Coluna com anos de PM do aluno em 2020 e 2022
df_passos_2021_anos_pm = df_2021.merge(df_2020[['NOME','ANOS_PM_2020']], on='NOME', how='left')
display(df_passos_2021_anos_pm.isna().sum())
df_passos_2021_anos_pm = df_passos_2021_anos_pm.merge(df_2022[['NOME','ANOS_PM_2022']], on="NOME", how='left')
display(df_passos_2021_anos_pm.isna().sum())

NOME                               0
INSTITUICAO_ENSINO_ALUNO_2021      0
FASE_2021                          0
TURMA_2021                         0
PONTO_VIRADA_2021                  0
SINALIZADOR_INGRESSANTE_2021       0
INDE_2021                          0
PEDRA_2021                         0
IAA_2021                           0
IEG_2021                           0
IPS_2021                           0
IDA_2021                           0
IPP_2021                           0
IPV_2021                           0
IAN_2021                           0
REC_EQUIPE_1_2021                  0
REC_EQUIPE_2_2021                  0
REC_EQUIPE_3_2021                  0
REC_EQUIPE_4_2021                  0
NIVEL_IDEAL_2021                   0
DEFASAGEM_2021                     0
ANOS_PM_2020                     229
dtype: int64

NOME                               0
INSTITUICAO_ENSINO_ALUNO_2021      0
FASE_2021                          0
TURMA_2021                         0
PONTO_VIRADA_2021                  0
SINALIZADOR_INGRESSANTE_2021       0
INDE_2021                          0
PEDRA_2021                         0
IAA_2021                           0
IEG_2021                           0
IPS_2021                           0
IDA_2021                           0
IPP_2021                           0
IPV_2021                           0
IAN_2021                           0
REC_EQUIPE_1_2021                  0
REC_EQUIPE_2_2021                  0
REC_EQUIPE_3_2021                  0
REC_EQUIPE_4_2021                  0
NIVEL_IDEAL_2021                   0
DEFASAGEM_2021                     0
ANOS_PM_2020                     229
ANOS_PM_2022                     229
dtype: int64

In [150]:
import math

def calculate_anos_pm_2020(x):
    if not math.isnan(x):
        return int(x + 1)
    else:
        return None

def calculate_anos_pm_2022(x):
    if not math.isnan(x):
        return int(x - 1)
    else:
        return None
    
def calculate_anos_pm(x, y):
    if not math.isnan(x):
        return x
    else:
        if not math.isnan(y):
            return y
        else:
            return None

In [151]:
# Anos PM a partir dos dados de 2020
df_passos_2021_anos_pm['ANOS_PM_2021_a'] = df_passos_2021_anos_pm['ANOS_PM_2020'].apply(calculate_anos_pm_2020)

In [152]:
# Anos PM a partir dos dados de 2022
df_passos_2021_anos_pm['ANOS_PM_2021_b'] = df_passos_2021_anos_pm['ANOS_PM_2022'].apply(calculate_anos_pm_2022)

In [153]:
# Coluna final combinando duas colunas criadas
df_passos_2021_anos_pm['ANOS_PM_2021'] = df_passos_2021_anos_pm.apply(lambda row: calculate_anos_pm(row['ANOS_PM_2021_a'], row['ANOS_PM_2021_b']), axis=1)

In [154]:
# Valor 0 para alunos novos
df_passos_2021_anos_pm.loc[df_passos_2021_anos_pm['SINALIZADOR_INGRESSANTE_2021'] == 'Ingressante', 'ANOS_PM_2021'] = 0

In [155]:
# Apenas 4 alunos sem informação da contagem de anos
df_passos_2021_anos_pm['ANOS_PM_2021'].isna().sum()

4

In [156]:
# Será utilizada abordagem de preenchimento com mediana
df_passos_2021_anos_pm['ANOS_PM_2021'].fillna(df_passos_2021_anos_pm['ANOS_PM_2021'].median(), inplace=True)

In [157]:
# Adição da nova coluna no DF
list_values_anos_pm_2021 = df_passos_2021_anos_pm['ANOS_PM_2021']
df_2021.insert(2, 'ANOS_PM_2021', list_values_anos_pm_2021)

# Criação coluna NIVEL_IDEAL_, DEFASAGEM

In [158]:
def ajuste_fase_alfa(x):
    if x.startswith('ALFA'):
        return x.replace('ALFA ','FASE 0')
    else:
        return x
    
def calculo_nivel_ideal_int(nivel_ideal, nivel_atual):
    if nivel_ideal != 'Não se Aplica':
        nivel_str = nivel_ideal.split( )[1]
        return int(nivel_str)
    else:
        return int(nivel_atual)

## 2020

Sem informação de nível ideal do aluno

In [170]:
df_2020['NIVEL_IDEAL_2020'] = None
df_2020['DEFASAGEM_2020'] = None

## 2021

In [159]:
# Ajuste nomenclatura fase Alfa
df_2021['NIVEL_IDEAL_2021'] = df_2021['NIVEL_IDEAL_2021'].apply(ajuste_fase_alfa)

In [160]:
df_2021['NIVEL_IDEAL_2021'].unique()

array(['Nível 3 (7o e 8o ano)', 'Nível 2 (5o e 6o ano)',
       'Nível 5 (1o EM)', 'Nível 1 (4o ano)', 'Nível 4 (9o ano)',
       'Nível 8 (Universitários)', 'Nível 6 (2o EM)',
       'FASE 0 (2o e 3o ano)', 'Nível 7 (3o EM)', 'Não se Aplica'],
      dtype=object)

In [161]:
# Calculo numero inteiro
df_2021['NIVEL_IDEAL_2021'] = df_2021.apply(lambda row: calculo_nivel_ideal_int(row['NIVEL_IDEAL_2021'], row['FASE_2021']), axis=1)
df_2021['NIVEL_IDEAL_2021'].unique()

array([3, 2, 5, 1, 4, 8, 6, 0, 7], dtype=int64)

## 2022

In [165]:
df_2022['NIVEL_IDEAL_2022'].unique()

array(['Fase 2 (5º e 6º ano)', 'Fase 3 (7º e 8º ano)', 'Fase 6 (2º EM)',
       'ALFA  (2º e 3º ano)', 'Fase 1 (4º ano)', 'Fase 4 (9º ano)',
       'Fase 8 (Universitários)', 'Fase 5 (1º EM)', 'Fase 7 (3º EM)'],
      dtype=object)

In [166]:
# Ajuste nomenclatura fase Alfa
df_2022['NIVEL_IDEAL_2022'] = df_2022['NIVEL_IDEAL_2022'].apply(ajuste_fase_alfa)

In [168]:
# Calculo numero inteiro
df_2022['NIVEL_IDEAL_2022'] = df_2022.apply(lambda row: calculo_nivel_ideal_int(row['NIVEL_IDEAL_2022'], row['FASE_2022']), axis=1)
df_2022['NIVEL_IDEAL_2022'].unique()

array([2, 3, 6, 0, 1, 4, 8, 5, 7], dtype=int64)

In [169]:
# Cálculo defasagem
df_2022['DEFASAGEM_2022'] = df_2022['NIVEL_IDEAL_2022'] - df_2022['FASE_2022']
df_2022

,NOME,ANO_INGRESSO_2022,ANOS_PM_2022,BOLSISTA_2022,FASE_2022,TURMA_2022,PONTO_VIRADA_2022,INDE_2022,PEDRA_2022,CG_2022,...,NOTA_MAT_2022,NOTA_ING_2022,QTD_AVAL_2022,REC_AVA_1_2022,REC_AVA_2_2022,REC_AVA_3_2022,REC_AVA_4_2022,NIVEL_IDEAL_2022,INDICADO_BOLSA_2022,DEFASAGEM_2022
0,ALUNO-2,2022,0,False,0,K,Não,7.676,Ametista,245,...,9.433,0.000,2,Mantido na Fase + Bolsa,Mantido na Fase atual,NaN,NaN,2,True,2
1,ALUNO-4,2022,0,False,2,J,Não,7.117,Ametista,451,...,5.167,0.000,3,Promovido de Fase,Mantido na Fase atual,Promovido de Fase,NaN,3,False,1
2,ALUNO-5,2019,3,False,2,L,Não,7.232,Ametista,415,...,7.500,0.000,3,Mantido na Fase atual,Promovido de Fase,Mantido na Fase atual,NaN,3,False,1
3,ALUNO-6,2022,0,False,2,K,Não,7.742,Ametista,221,...,8.000,0.000,3,Mantido na Fase atual,Promovido de Fase,Mantido na Fase atual,NaN,2,False,0
4,ALUNO-7,2022,0,False,1,U,Não,7.407,Ametista,357,...,6.500,0.000,2,Promovido de Fase,Promovido de Fase,NaN,NaN,2,False,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,ALUNO-1342,2022,0,False,2,K,Não,8.150,Topázio,99,...,9.500,0.000,3,Mantido na Fase atual,Promovido de Fase,Mantido na Fase atual,NaN,2,False,0
858,ALUNO-1343,2018,4,False,2,K,Não,5.675,Quartzo,763,...,2.000,0.000,3,Mantido na Fase atual,Promovido de Fase,Mantido na Fase atual,NaN,4,False,2
859,ALUNO-1346,2022,0,False,0,U,Sim,8.136,Topázio,105,...,8.833,0.000,2,Promovido de Fase,Promovido de Fase,NaN,NaN,1,False,1
860,ALUNO-1348,2018,4,True,4,P,Não,6.750,Ágata,567,...,7.167,5.867,4,Mantido na Fase atual,Mantido na Fase atual,Promovido de Fase,Promovido de Fase,5,False,1
861,ALUNO-1349,2022,0,False,3,M,Não,6.400,Ágata,662,...,3.833,6.000,4,Promovido de Fase,Mantido na Fase atual,Promovido de Fase,Mantido na Fase + Bolsa,5,True,2

# Colunas instituição de ensino e bolsista

In [172]:
# Função para criar coluna bolsista nos dfs 2020 e 2022
def verifica_bolsista(x):
    if x != 'Escola Pública':
        return 1
    else:
        return 0

In [173]:
df_2020['BOLSISTA_2020'] = df_2020['INSTITUICAO_ENSINO_ALUNO_2020'].apply(verifica_bolsista)
df_2021['BOLSISTA_2021'] = df_2021['INSTITUICAO_ENSINO_ALUNO_2021'].apply(verifica_bolsista)

In [174]:
df_2021['BOLSISTA_2021'].value_counts()

BOLSISTA_2021
0    557
1    129
Name: count, dtype: int64

In [175]:
df_2020['BOLSISTA_2020'].value_counts()

BOLSISTA_2020
0    598
1    129
Name: count, dtype: int64

In [176]:
df_2022['BOLSISTA_2022'].value_counts()

BOLSISTA_2022
False    754
True     108
Name: count, dtype: int64

In [177]:
# Coluna de instituição de ensino no DF 2022
df_2022['INSTITUICAO_ENSINO_ALUNO_2021'] = 'Não informado'

# Criação coluna Ano Pesquisa

In [179]:
df_2020['ANO_PESQUISA'] = 2020
df_2021['ANO_PESQUISA'] = 2021
df_2022['ANO_PESQUISA'] = 2022

In [178]:
# Colunas em comum (2020-2021-2022): ['NOME','ANO_PESQUISA','INSTITUICAO_ENSINO_ALUNO','BOLSISTA','ANOS_PM','FASE','TURMA','PONTO_VIRADA','INDE',
# 'PEDRA', 'IAA','IEG','IPS','IDA','IPP','IPV','IAN','NIVEL_IDEAL', 'DEFASAGEM']